# Generated by Django 5.0.4 on 2024-05-07 11:36

import django.db.models.deletion
import pathlib
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('Z:/Documents/_Works/Tests/two_cabinets/media/img'), verbose_name='Изображение')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateTimeField(verbose_name='Дата начала обработки')),
                ('dateEndPlan', models.DateTimeField(verbose_name='Дата сдачи плановая')),
                ('dateCompleted', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата выполнения')),
                ('isAccepted', models.BooleanField(blank=True, default=None, null=True, verbose_name='Принято заказчиком?')),
                ('dateAccepted', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Когда принято')),
                ('score', models.SmallIntegerField(null=True, verbose_name='Оценка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.offer', verbose_name='Предложение')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('dateRelease', models.DateField(verbose_name='Дата выпуска')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(unique=True, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('Z:/Documents/_Works/Tests/two_cabinets/media/img'), verbose_name='Фото')),
                ('gender', models.CharField(choices=[(None, '-- Выберите --'), ('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=1, verbose_name='Пол')),
                ('dateReg', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('rate', models.FloatField(blank=True, null=True, verbose_name='Рейтинг')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.city', verbose_name='Город')),
                ('specializations', models.ManyToManyField(blank=True, to='app.category', verbose_name='Специализации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
