# Generated by Django 5.0.4 on 2024-05-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_offer_number_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dateAccepted',
        ),
        migrations.AddField(
            model_name='offer',
            name='processPeriod',
            field=models.IntegerField(default=3, verbose_name='Дней на выполнение (min)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='dateCompleted',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateEndPlan',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата сдачи плановая'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateStart',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата начала обработки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='Номер'),
        ),
    ]
