# Generated by Django 5.0.4 on 2024-05-10 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_offer_isdeleted_order_isdeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.offer', verbose_name='Проект'),
        ),
    ]
