# Generated by Django 5.0.4 on 2024-05-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_order_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='cost',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Стоимость'),
        ),
    ]
