# Generated by Django 5.0.4 on 2024-05-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_offer_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dateCompleted',
            new_name='dateComplete',
        ),
    ]
