# Generated by Django 5.0.4 on 2024-05-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_order_isaccepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(max_length=255, null=True, verbose_name='URL'),
        ),
    ]
