# Generated by Django 5.0.4 on 2024-05-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_category_slug_alter_city_slug_alter_offer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateEndFact',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата выполнения (факт)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateComplete',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateEndPlan',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата выполнения (план)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='score',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Оценка'),
        ),
    ]
