# Generated by Django 5.0.4 on 2024-05-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_offer_processperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='processPeriod',
            field=models.IntegerField(verbose_name='Дней на выполнение (min)'),
        ),
    ]
