# Generated by Django 5.0.4 on 2024-05-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_offer_processperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(default='', max_length=500, verbose_name='Описание'),
        ),
    ]
