# Generated by Django 5.0.4 on 2024-05-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_order_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dateComplete',
        ),
        migrations.AddField(
            model_name='order',
            name='dateAccept',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата принятия'),
        ),
    ]
