# Generated by Django 5.0.4 on 2024-05-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_order_datecomplete_order_dateaccept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Рейтинг'),
        ),
    ]
